services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: budget_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      args:
        DATABASE_URL: postgres://postgres:password@postgres:5432/budget_tracker
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/budget_tracker
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./static:/app/static:ro
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
