version = 4.1.1
archive_dir = /etc/letsencrypt/archive/budgetfun.ca
cert = /etc/letsencrypt/live/budgetfun.ca/cert.pem
privkey = /etc/letsencrypt/live/budgetfun.ca/privkey.pem
chain = /etc/letsencrypt/live/budgetfun.ca/chain.pem
fullchain = /etc/letsencrypt/live/budgetfun.ca/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 364d5b7f4fa16a9e64accdcc6c464789
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
budgetfun.ca = /var/www/certbot
www.budgetfun.ca = /var/www/certbot
