use crate::models::BudgetCategory;

pub fn get_default_categories() -> Vec<BudgetCategory> {
    vec![
        BudgetCategory {
            name: "INCOME".to_string(),
            subcategories: vec![
                "Salary/Wages".to_string(),
                "Freelance/Gig Work".to_string(),
                "Business Income".to_string(),
                "Investment Returns".to_string(),
                "Dividends".to_string(),
                "Interest Income".to_string(),
                "Rental Income".to_string(),
                "Government Benefits".to_string(),
                "Tax Refund".to_string(),
                "Side Hustle".to_string(),
                "Cryptocurrency Gains".to_string(),
                "Pension".to_string(),
                "Gifts/Inheritance".to_string(),
                "Other Income".to_string(),
            ],
            is_income: true,
        },
        BudgetCategory {
            name: "HOUSING".to_string(),
            subcategories: vec![
                "Rent/Mortgage".to_string(),
                "Property Tax".to_string(),
                "Home Insurance".to_string(),
                "HOA/Condo Fees".to_string(),
                "Utilities - Electricity".to_string(),
                "Utilities - Gas".to_string(),
                "Utilities - Water".to_string(),
                "Utilities - Trash/Recycling".to_string(),
                "Internet".to_string(),
                "Cable/Satellite TV".to_string(),
                "Home Security System".to_string(),
                "Maintenance/Repairs".to_string(),
                "Home Improvement".to_string(),
                "Landscaping/Lawn Care".to_string(),
                "Cleaning Service".to_string(),
                "Storage Unit".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "TRANSPORTATION".to_string(),
            subcategories: vec![
                "Car Payment".to_string(),
                "Car Insurance".to_string(),
                "Gasoline".to_string(),
                "Car Maintenance/Repairs".to_string(),
                "Registration/License".to_string(),
                "Parking".to_string(),
                "Tolls".to_string(),
                "Public Transportation".to_string(),
                "Uber/Lyft".to_string(),
                "Taxi".to_string(),
                "Car Rental".to_string(),
                "Motorcycle/Scooter".to_string(),
                "Bike Maintenance".to_string(),
                "Electric Vehicle Charging".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "FOOD & DINING".to_string(),
            subcategories: vec![
                "Groceries".to_string(),
                "Restaurants".to_string(),
                "Fast Food".to_string(),
                "Coffee Shops".to_string(),
                "Food Delivery (DoorDash, Uber Eats)".to_string(),
                "Meal Kits (HelloFresh, Blue Apron)".to_string(),
                "Work Lunches".to_string(),
                "Snacks/Convenience Store".to_string(),
                "Alcohol".to_string(),
                "Special Occasions/Catering".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "HEALTH & FITNESS".to_string(),
            subcategories: vec![
                "Health Insurance".to_string(),
                "Dental Insurance".to_string(),
                "Vision Insurance".to_string(),
                "Life Insurance".to_string(),
                "Doctor Visits".to_string(),
                "Dental Care".to_string(),
                "Eye Care".to_string(),
                "Prescriptions".to_string(),
                "Over-the-counter Medicine".to_string(),
                "Gym Membership".to_string(),
                "Personal Trainer".to_string(),
                "Fitness Classes".to_string(),
                "Fitness Apps/Equipment".to_string(),
                "Mental Health/Therapy".to_string(),
                "Alternative Medicine".to_string(),
                "Medical Devices".to_string(),
                "Pet Insurance".to_string(),
                "Veterinary Care".to_string(),
                "Pet Food/Supplies".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "ENTERTAINMENT & LIFESTYLE".to_string(),
            subcategories: vec![
                "Netflix".to_string(),
                "Disney+".to_string(),
                "Hulu".to_string(),
                "Amazon Prime Video".to_string(),
                "HBO Max".to_string(),
                "Apple TV+".to_string(),
                "YouTube Premium".to_string(),
                "Spotify".to_string(),
                "Apple Music".to_string(),
                "Pandora".to_string(),
                "Gaming Subscriptions (Xbox, PlayStation)".to_string(),
                "Steam/Gaming".to_string(),
                "Movies/Theater".to_string(),
                "Concerts/Events".to_string(),
                "Books/Audible".to_string(),
                "Magazines/Newspapers".to_string(),
                "Hobbies".to_string(),
                "Sports/Recreation".to_string(),
                "Vacation/Travel".to_string(),
                "Dating/Social".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "TECHNOLOGY & COMMUNICATION".to_string(),
            subcategories: vec![
                "Cell Phone Bill".to_string(),
                "Home Internet".to_string(),
                "Cloud Storage (iCloud, Google Drive)".to_string(),
                "Software Subscriptions".to_string(),
                "VPN Service".to_string(),
                "Computer/Electronics".to_string(),
                "Phone/Tablet".to_string(),
                "Tech Repairs".to_string(),
                "Domain/Hosting".to_string(),
                "Online Tools/Apps".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "EDUCATION & DEVELOPMENT".to_string(),
            subcategories: vec![
                "Student Loan Payment".to_string(),
                "Tuition".to_string(),
                "Books/Supplies".to_string(),
                "Online Courses (Udemy, Coursera)".to_string(),
                "Professional Development".to_string(),
                "Conferences/Workshops".to_string(),
                "Certifications".to_string(),
                "Language Learning (Duolingo Plus)".to_string(),
                "Trade School".to_string(),
                "Tutoring".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "PERSONAL CARE & SHOPPING".to_string(),
            subcategories: vec![
                "Clothing".to_string(),
                "Shoes".to_string(),
                "Personal Care Items".to_string(),
                "Haircut/Salon".to_string(),
                "Spa/Beauty Treatments".to_string(),
                "Laundry/Dry Cleaning".to_string(),
                "Amazon Prime".to_string(),
                "Online Shopping".to_string(),
                "Department Stores".to_string(),
                "Cosmetics/Skincare".to_string(),
                "Jewelry/Accessories".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "FINANCIAL & BUSINESS".to_string(),
            subcategories: vec![
                "Bank Fees".to_string(),
                "Credit Card Interest".to_string(),
                "Investment Fees".to_string(),
                "Tax Preparation".to_string(),
                "Accounting/Bookkeeping".to_string(),
                "Legal Fees".to_string(),
                "Business Expenses".to_string(),
                "Professional Services".to_string(),
                "Financial Planning".to_string(),
                "Late Fees/Penalties".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "FAMILY & CHILDCARE".to_string(),
            subcategories: vec![
                "Childcare/Daycare".to_string(),
                "Babysitting".to_string(),
                "School Fees".to_string(),
                "Kids Activities/Sports".to_string(),
                "Kids Clothing".to_string(),
                "Toys/Games".to_string(),
                "Birthday Parties/Gifts".to_string(),
                "Family Outings".to_string(),
                "Child Support".to_string(),
                "Elder Care".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "GIVING & DONATIONS".to_string(),
            subcategories: vec![
                "Charitable Donations".to_string(),
                "Religious Donations".to_string(),
                "Political Donations".to_string(),
                "Gifts for Others".to_string(),
                "Holiday Gifts".to_string(),
                "Wedding Gifts".to_string(),
                "Fundraising".to_string(),
                "Sponsorships".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "SAVINGS & INVESTMENTS".to_string(),
            subcategories: vec![
                "Emergency Fund".to_string(),
                "Retirement Savings (401k, IRA)".to_string(),
                "Investment Account".to_string(),
                "Stocks/ETFs".to_string(),
                "Cryptocurrency".to_string(),
                "College Savings (529)".to_string(),
                "HSA Contributions".to_string(),
                "CD/Bonds".to_string(),
                "Real Estate Investment".to_string(),
                "Business Investment".to_string(),
            ],
            is_income: false,
        },
        BudgetCategory {
            name: "DEBT PAYMENTS".to_string(),
            subcategories: vec![
                "Credit Card Payment".to_string(),
                "Personal Loan".to_string(),
                "Student Loan".to_string(),
                "Medical Debt".to_string(),
                "Business Loan".to_string(),
                "Payday Loan".to_string(),
                "Family Loan".to_string(),
                "Other Debt".to_string(),
            ],
            is_income: false,
        },
    ]
}
